/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LogRouteImport } from './routes/log'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgressionExerciseIdRouteImport } from './routes/progression.$exerciseId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionExerciseIdRoute = ProgressionExerciseIdRouteImport.update({
  id: '/progression/$exerciseId',
  path: '/progression/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/log': typeof LogRoute
  '/privacy': typeof PrivacyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/progression/$exerciseId': typeof ProgressionExerciseIdRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/log': typeof LogRoute
  '/privacy': typeof PrivacyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/progression/$exerciseId': typeof ProgressionExerciseIdRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/log': typeof LogRoute
  '/privacy': typeof PrivacyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/progression/$exerciseId': typeof ProgressionExerciseIdRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/log'
    | '/privacy'
    | '/auth/callback'
    | '/progression/$exerciseId'
    | '/api/auth/session'
    | '/api/auth/signout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/log'
    | '/privacy'
    | '/auth/callback'
    | '/progression/$exerciseId'
    | '/api/auth/session'
    | '/api/auth/signout'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/log'
    | '/privacy'
    | '/auth/callback'
    | '/progression/$exerciseId'
    | '/api/auth/session'
    | '/api/auth/signout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  LogRoute: typeof LogRoute
  PrivacyRoute: typeof PrivacyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProgressionExerciseIdRoute: typeof ProgressionExerciseIdRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression/$exerciseId': {
      id: '/progression/$exerciseId'
      path: '/progression/$exerciseId'
      fullPath: '/progression/$exerciseId'
      preLoaderRoute: typeof ProgressionExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  LogRoute: LogRoute,
  PrivacyRoute: PrivacyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProgressionExerciseIdRoute: ProgressionExerciseIdRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
